name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Use public npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Uncomment below if you want to keep history
          # keep_files: true
